MONITOR ${NUT_UPS_NAME}@localhost 1 ${NUT_USER_NAME} ${NUT_USER_PASS} master

NOTIFYFLAG ONLINE	EXEC
NOTIFYFLAG ONBATT	EXEC
NOTIFYFLAG LOWBATT	EXEC
NOTIFYFLAG FSD	        EXEC
NOTIFYFLAG COMMOK	EXEC
NOTIFYFLAG COMMBAD	EXEC
NOTIFYFLAG SHUTDOWN	EXEC
NOTIFYFLAG REPLBATT	EXEC
NOTIFYFLAG NOCOMM	EXEC
NOTIFYFLAG NOPARENT	EXEC

LOGLEVEL 5

NOTIFYCMD /usr/local/bin/upsnotify-wrapper.sh
